---
abstract: 'Tapper - Program run control for test program automation'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Tapper::Test: 3.000010
  Test::Fixture::DBIC::Schema: 0
  Test::MockModule: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-PRC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Path: 0
  IPC::Open3: 0
  List::Util: 0
  Log::Log4perl: 0
  Moose: 0
  Tapper::Base: 3.000010
  Tapper::Remote: 3.000010
  YAML: 0.72
  common::sense: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-PRC
  repository: git://github.com/amd/Tapper-Reports-PRC.git
version: 3.000010
